version: '3.1'
services:
  backend:
    image: maven:3.8.4-openjdk-17-slim
    ports:
      - 8080:8080
    volumes:
      - ./recruitmentApplication:/usr/src/mymaven:rw
    working_dir: /usr/src/mymaven
    command: mvn spring-boot:run
